# Development environment configuration
server:
  # The HTTP port of the server, the default is 80
  port: 8088
  servlet:
    # Access path of the application
    context-path: /
  undertow:
    # Set the number of IO threads. It mainly performs non-blocking tasks. They will be responsible for multiple connections. The default setting is one thread per CPU core. Do not set too large. If it is too large, the startup project will report an error: too many open files
    io-threads: 16
    # Blocking task thread pool, when executing similar servlet request blocking IO operations, undertow will get threads from this thread pool. Its value setting depends on the blocking coefficient of system threads executing tasks. The default value is the number of IO threads*8
    worker-threads: 256
    # The following configuration will affect the buffers. These buffers will be used for server connection IO operations. It is a bit similar to netty's pooled memory management. The space size of each buffer is used. The smaller the space, the more fully utilized. Don't set too large, so as not to affect other Application, just suitable
    buffer-size: 1024
    # Whether to allocate direct memory (out-of-heap memory directly allocated by NIO)
    direct-buffers: true
# Log configuration
logging:
  config: classpath:log4j2.xml
# Spring Configuration
spring:
  datasource:
    dynamic:
      hikari:  # For global hikariCP parameters, all values are consistent with the default. (The currently supported parameters are as follows, don't set it randomly if you don't know the meaning)
        connection-timeout: 30000
        idle-timeout: 25000
        max-lifetime: 30000
        validation-timeout: 3000
        max-pool-size: 15
        min-idle: 10
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
      primary: master #Set the default data source or data source group, the default value is master
      strict: false #Set the strict mode, the default false is not started. After starting, an exception will be thrown when the specified data source is matched, and the default data source will be used if it is not started.
      datasource:
        master:
          username: root
          password: 521
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/crown2?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          hikari:
            is-read-only: false
        slave:
          username: root
          password: 521
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/crown2?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          hikari:
            is-read-only: true
  aop:
    auto: true
    proxy-target-class: true
  # Template engine
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # Disable caching
    cache: false
  # Resource information
  messages:
    # Internationalized resource file path
    basename: static/i18n/messages
  # File Upload
  servlet:
    multipart:
      # Single file size
      max-file-size:  10MB
      # Set the total uploaded file size
      max-request-size:  20MB
  # Service module
  devtools:
    restart:
      # Hot deployment switch
      enabled: true
mybatis-plus:
  configuration:
    cache-enabled: false
    default-executor-type: reuse
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: sys_
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
    banner: false
    super-mapper-class: org.crown.framework.mapper.BaseMapper
  type-enums-package: org.crown.common.enums,org.crown.framework.enums
  type-aliases-package: org.crown.project.*.*.domain
  type-handlers-package: org.crown.framework.mybatisplus.typehandler
# Project related configuration
crown:
  email:
    enabled: false
    send: 10001@qq.com
  # Code generation
  generator:
    author: Caratacus
    package-path: org.crown.project.monitor
  # Example demo switch
  demo:
    enabled: false
    # Get ip address switch
  address:
    enabled: true
  password:
    # Wrong password {maxRetryCount} locked for 10 minutes
    maxRetryCount: 5
  path:
    file-path: /develop/crown/filepath/
    resource-handler: /profile/**
    resource-path: /profile/
    prefix:
      avatar: avatar/
      download: download/
      upload: upload/
  xss:
    enabled: true
    exclude-fields:
      - noticeContent
    exclude-urls:
      - /system/notice/*
shiro:
  index-url: /index
  login-url: /login
  unauth-url: /unauth
  session:
    db-sync-period: 1
    expire-time: 30
    validation-interval: 10
    max-session: 1
    kickout-after: false
  remember-me-cookie:
    domain:
    path: /
    http-only: true
    max-age: 1